SELECT
    PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, "NONE") AS TLNO
FROM PATIENT
WHERE AGE<=12 AND GEND_CD="W"
ORDER BY AGE DESC, PT_NAME ASC

/*
NULLIF와 IFNULL의 차이에 주의

NULLIF(A,B)
A=B인 경우 NULL 반환, A!=인 경우 A 반환

IFNULL(A,B)
A가 NULL이면 B를 반환
*/
