SELECT 
    MEMBER_ID,
    MEMBER_NAME,
    GENDER,
    DATE_FORMAT(DATE_OF_BIRTH,"%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE 
    GENDER="W" 
    AND DATE_OF_BIRTH LIKE "_____03-%" 
    #AND MONTH(DATE_OF_BIRTH)=3 
    #AND DATE_FORMAT(DATE_OF_BIRTH,"%m")="03" 
    
    AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;
