SELECT 
    DATE_FORMAT(SALES_DATE,"%Y-%m-%d") SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE>="2022-03-01" AND SALES_DATE<"2022-04-01"

UNION ALL

SELECT
    DATE_FORMAT(SALES_DATE,"%Y-%m-%d") SALES_DATE,
    PRODUCT_ID,
    NULL AS USER_ID,
    SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE>="2022-03-01" AND SALES_DATE<"2022-04-01"

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;

#UNION ALL을 통해
#두 테이블에서 원하는 데이터를 추출하고 합침
#존재하지 않는 컬럼의 값을 모두 NULL로 처리하는 방법 알기
